---
- name: Process all exporters
  ansible.builtin.include_tasks:
    file: process_exporter.yml
  loop: '{{ prometheus_target_exporter +
         ([] if prometheus_target_skip_default_exporters else prometheus_target_default_exporters) }}'
  loop_control:
    loop_var: item

- name: Run handlers
  ansible.builtin.include_tasks:
    file: handlers.yml
  when: changed | default(false)
