---
- name: Process exporters (yaml strategy)
  ansible.builtin.include_tasks:
    file: yaml_item.yml
  loop: '{{ prometheus_target_exporter +
         ([] if prometheus_target_skip_default_exporters else prometheus_target_default_exporters) }}'
  loop_control:
    loop_var: _exporter_item

- name: Export fact
  ansible.builtin.set_fact:
    changed: '{{ changed or (_yaml_changed | default(false)) }}'
